export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export TERMINAL="kitty"
export DIFFPROG="nvim -d"

export PATH=/usr/local/bin:$PATH
export PATH=$HOME/.local/bin:$PATH
export PATH=/usr/local/bin:$PATH
export PATH=/usr/bin:$PATH
export PATH=/bin:$PATH
export PATH=/usr/local/sbin:$PATH
export PATH=/usr/lib/jvm/default/bin:$PATH
export PATH=/usr/bin/site_perl:$PATH
export PATH=/usr/bin/vendor_perl:$PATH
export PATH=/usr/bin/core_perl:$PATH
export PATH=$HOME/.config/zsh/fzf/fzf/bin:$PATH
export PATH=$HOME/.dwm/statusbar:$PATH
export PATH="$PATH:$(find /opt -type d -name bin | paste -sd: -)" # all /opt/**/bin (chatgpt)
export PATH=$HOME/local/bin/statusbar:$PATH # Set in .xsession (before dwmblocks starts)
export PATH=$HOME/.dwm/statusbar:$PATH
export PATH=/usr/lib/wireshark/extcap:$PATH

export JAVA_HOME="/usr/lib/jvm/default-runtime"
export npm_config_prefix="$HOME/.local"
export GPG_TTY=$(tty)

if [ -f "$ZDOTDIR/projenv" ]; then source "$ZDOTDIR/projenv"; fi

# Dotfile management with antigen
if [ -f "$XDG_DATA_HOME/antidot/env.sh" ]; then source "$XDG_DATA_HOME/antidot/env.sh"; fi
if [ -f "$XDG_DATA_HOME/antidot/alias.sh" ]; then source "$XDG_DATA_HOME/antidot/alias.sh"; fi

if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
    export MOZ_ENABLE_WAYLAND=1
fi

