#!/bin/dash
chrg=$(acpi -b | awk '{ print $3 }' | tr -d ',')

if [ $chrg = "Charging" ]
then
	chrg=
else
	chrg=''
fi

bat=$(acpi -b | awk '{ print $4 }' | tr -d ',%')

if [ $bat -ge 80 ]
then
	echo $chrg $bat%
elif [ $bat -ge 60 ]
then
	echo $chrg $bat%
elif [ $bat -ge 40 ]
then
	echo $chrg $bat%
elif [ $bat -ge 20 ]
then
	echo $chrg $bat%
else
	echo $chrg $bat%
fi
