#!/bin/dash

cpu_usage=$(top -b -n1 | grep "Cpu(s)" | awk '{printf "%.1f%", $2 + $4}')
temp=$(sensors | grep "Tctl" | awk '{printf "%.1f", $2}')
wholetemp=$(printf "%.0f" $temp)

if [ $wholetemp -ge 75 ]
then
	echo $cpu_usage $temp° 
elif [ $wholetemp -ge 60 ]
then
	echo $cpu_usage $temp°
else 
	echo $cpu_usage $temp°
fi
