#!/bin/dash

amixer sget Master | grep '\[off\]' > /dev/null && mute=1 || mute=0
vol=$(amixer sget Master | grep 'Mono:' | awk -F'[][]' '{ print $2 }' | tr -d '%')

if [ $mute -eq 1 ]
then
	echo 婢M$vol%
elif [ $vol -eq 0 ]
then
	echo 婢$vol%
elif [ $vol -gt 40 ]
then
	echo 墳$vol%
elif [ $vol -gt 20 ]
then
	echo 奔$vol%
elif [ $vol -gt 10 ]
then
	echo 奔$vol%
elif [ $vol -ge 0 ]
then
	echo 奄$vol%
fi
