test = { command = "echo hello | grep hello" }

[tlp.freq]
lock = { command = "sudo mv /etc/tlp.d/12-cpu-locked-freq.conf{.disabled,} && sudo tlp start" }
unlock = { command = "sudo mv /etc/tlp.d/12-cpu-locked-freq.conf{,.disabled} && sudo tlp start" }


[tlp.boost]
desc = "manage tlp performance configs"
enable = { command = "sudo mv /etc/tlp.d/11-boost.conf{.disabled,} && sudo tlp start" }
disable = { command = "sudo mv /etc/tlp.d/11-boost.conf{,.disabled} && sudo tlp start" }

[tlp.boost.gpu]
enable = { command = "sudo mv /etc/tlp.d/11-gpu-boost.conf{.disabled,} && sudo tlp start" }
disable = { command = "sudo mv /etc/tlp.d/11-gpu-boost.conf{,.disabled} && sudo tlp start" }

[wl]
desc = "manage wireless cards"
man = { command = "sudo iw wlp166s0 set type managed", desc = "set wifi card in managed mode" }
mon = { command = "sudo iw wlp166s0 set monitor none", desc = "set wifi card in monitor mode" }
up = { command = "sudo ip link set wlp166s0 up", desc = "set wifi card up" }
down = { command = "sudo ip link set wlp166s0 down", desc = "set wifi card down" }

[res]
desc = "restart/redo various things"
bl = { command = "sudo systemctl restart bluetooth", desc = "restart bluetooth" }
poly = { command = "sh ~/.config/polybar/launch.sh", desc = "restart polybar" }
altswap = { command = "setxkbmap -option altwin:swap_alt_win", desc = "redo alt/win swap" }
xset = { command = "xset r rate 450 60", desc = "redo xset rate" }
feh = { command = "sh ~/.fehbg", desc = "redo feh" }
# TODO: This doesn't work well with passthrough. Add aliases to other commands of some sort
x = { command = "srun res poly; srun res xset; srun res feh", desc = "multi restart/redo to fix X related issues" }

[rcl]
# The reason for verbose is because this is usually runs in its own terminal (for indefinite period of time)
sch = { command = "rclone mount drive:/School ~/sch/drive/ --vfs-cache-mode full --verbose --poll-interval 5m --vfs-write-back 10s", desc = "mount school drive" }
obs = { command = "rclone mount crypt-drive:/obsidian/event-log ~/dc/obsidian/event-log --vfs-cache-mode full --verbose --poll-interval 5m --vfs-write-back 30s", desc = "mount encrypted obsidian drive" }

[git]
# https://stackoverflow.com/a/21189710
init-branches = { command = "for b in `git branch -r | grep -v -- '->'`; do echo $b; done", a = {}}

[pac]
desc = "pacman commands"

[pac.list]
desc = "list pacman pacakges from log"
in = { command = "grep -i installed /var/log/pacman.log", desc = "installed package list" }
upg = { command = "grep -i upgraded /var/log/pacman.log", desc = "upgraded package list" }
rem = { command = "grep -i removed /var/log/pacman.log", desc = "removed package list" }

[zplug]
upg = { command = "zplug install && zplug update && zplug load && zplug clean", desc = "upgrade zplug plugins" }

[tasker]
desc = "remotely control phone"
release-bl = { command = 'curl "https://joinjoaomgcd.appspot.com/_ah/api/messaging/v1/sendPush?apikey=$(cat ~/.secrets/join.apikey)&deviceNames=S22%20Ultra&text=release-buds-fe&title=Galaxy%20Buds%20FE%20released&category=silently%20notify"', desc = "release galaxy buds fe" }
